### ISSUE TITLE
[已修复]不行，跑不起来，no Bundle URL present.你先测下

### ISSUE THREAD

**Issue by w819314930** [YiHuaXie/NNHybrid#1]

**Comment by YiHuaXie** [comment]
我不知道你是怎么操作的，因为项目里没有打jsbundle包，只能调试，需要启用npm start后再在Xcode里运行项目的，具体的步骤在README里

**Comment by w819314930** [comment]
我不知道怎么上传图片---我qq 819314930   可以加一下吗

wpdeMacBook-Pro:NNHybrid-master wp$ npm start

> NNHybird@0.0.1 start /Users/wp/Documents/RN/NNHybrid-master
> node node_modules/react-native/local-cli/cli.js start

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/wp/Documents/RN/NNHybrid-master 

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./navigator/AppNavigator` from `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/App.js`: The module `./navigator/AppNavigator` could not be found from `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/App.js`. Indeed, none of these files exist:
  * `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/navigator/AppNavigator(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/navigator/AppNavigator/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 4.0% (57/284), failed.

::ffff:192.168.123.106 - - [03/Jun/2019:03:03:05 +0000] "GET /index.bundle?platform=ios HTTP/1.1" 200 - "-" "NNHybridiOS/1 CFNetwork/978.0.7 Darwin/18.5.0"
::ffff:192.168.123.106 - - [03/Jun/2019:03:03:05 +0000] "GET /index.bundle?platform=ios HTTP/1.1" 200 - "-" "NNHybridiOS/1 CFNetwork/978.0.7 Darwin/18.5.0"
Launching Dev Tools...
::ffff:192.168.123.106 - - [03/Jun/2019:03:03:05 +0000] "GET /launch-js-devtools HTTP/1.1" 200 - "-" "NNHybridiOS/1 CFNetwork/978.0.7 Darwin/18.5.0"
error: bundling failed: Error: Unable to resolve module `./navigator/AppNavigator` from `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/App.js`: The module `./navigator/AppNavigator` could not be found from `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/App.js`. Indeed, none of these files exist:
  * `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/navigator/AppNavigator(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/wp/Documents/RN/NNHybrid-master/NNHybridRN/navigator/AppNavigator/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wp/Documents/RN/NNHybrid-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
